---
title: Mohamed Ali Ghouma - CV
layout: default
---
markdown: kramdown
theme: jekyll-theme-cayman
include:
  - style.css
  - script.js  
title: "Mohamed Ali Ghouma - DevOps Cloud SRE Senior"
description: "Mohamed Ali Ghouma"
theme: jekyll-theme-cayman

# Optional settings for SEO and social sharing
author:
  name: "Mohamed Ali Ghouma"
  email: "ghouma.mohamed.ali@gmail.com"
  LinkedIn: [Mohamed Ali Ghouma](https://www.linkedin.com/in/mohamed-ali-g/)

# Social media links (if any)
