---
title: Mohamed Ali Ghouma - CV
layout: default
---

# Mohamed Ali GHOUMA
**Ingénieur DevOps Cloud SRE Senior**  
**Contact:**  
Phone: +33 0758151884  
Email: [ghouma.mohamed.ali@gmail.com](mailto:ghouma.mohamed.ali@gmail.com)  
LinkedIn: [Mohamed Ali Ghouma](https://www.linkedin.com/in/mohamed-ali-g/)

---

## Compétences Techniques

<!-- Rest of your content -->
